# Generated by Django 3.1 on 2020-08-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
            ],
            options={
                'unique_together': {('date', 'school')},
            },
        ),
        migrations.CreateModel(
            name='Course_Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('Dname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.dname')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.week')),
            ],
            options={
                'unique_together': {('date', 'course', 'week', 'Dname')},
            },
        ),
    ]
