# Generated by Django 3.1 on 2020-08-08 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField()),
                ('board_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('school_id', models.IntegerField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=200)),
                ('school_city', models.CharField(max_length=100)),
                ('school_state', models.CharField(max_length=200)),
                ('registration_date', models.DateField()),
                ('total_teachers', models.IntegerField()),
                ('total_students', models.IntegerField()),
                ('board', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.boards')),
            ],
        ),
    ]
